workflows:
  android-build:
    name: Android Build for F-Droid
    max_build_duration: 30
    working_directory: mobile-app
    environment:
      flutter: stable
      groups:
        - android-signing
      vars:
        ANDROID_KEYSTORE_PASSWORD: "Echo1234!"
        ANDROID_KEYSTORE_ALIAS: "upload"
        ANDROID_KEYSTORE_KEY_PASSWORD: "Echo1234!"
    scripts:
      - name: Debug Environment
        script: |
          #!/bin/bash
          set -x  # Print commands as they run
          echo "Starting debug..."
          if [ -z "$ANDROID_KEYSTORE" ]; then
            echo "ERROR: ANDROID_KEYSTORE is empty or unset"
            exit 1
          else
            echo "ANDROID_KEYSTORE length: ${#ANDROID_KEYSTORE}"
            echo "ANDROID_KEYSTORE starts with: ${ANDROID_KEYSTORE:0:10}"
          fi
      - name: Decode Keystore
        script: |
          echo "$ANDROID_KEYSTORE" | base64 -d > keystore.jks
      - name: Get Flutter Dependencies
        script: flutter pub get
      - name: Build Signed APK
        script: |
          flutter build apk --release \
            --keystore-path keystore.jks \
            --keystore-password "$ANDROID_KEYSTORE_PASSWORD" \
            --keystore-key-alias "$ANDROID_KEYSTORE_ALIAS" \
            --keystore-key-password "$ANDROID_KEYSTORE_KEY_PASSWORD"
    artifacts:
      - build/**/outputs/**/*.apk