workflows:
  android-build:
    name: Android Build for F-Droid
    max_build_duration: 30
    environment:
      flutter: stable  # Uses latest stable Flutter (e.g., 3.19.x as of 2025)
      android_signing:
        - keystore_reference
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mikuchan@example.com