workflows:
  android-build:
    name: Android Build for F-Droid
    max_build_duration: 30
    working_directory: mobile-app  # Run all scripts in mobile-app/
    environment:
      flutter: stable
      groups:
        - android-signing
      vars:
        ANDROID_KEYSTORE_PASSWORD: "Echo1234!"
        ANDROID_KEYSTORE_ALIAS: "upload"
        ANDROID_KEYSTORE_KEY_PASSWORD: "Echo1234!"
    scripts:
      - name: Decode Keystore
        script: |
          echo "$ANDROID_KEYSTORE" | base64 -d > keystore.jks
      - name: Get Flutter Dependencies
        script: flutter pub get
      - name: Build Signed APK
        script: |
          flutter build apk --release \
            --keystore-path keystore.jks \
            --keystore-password "$ANDROID_KEYSTORE_PASSWORD" \
            --keystore-key-alias "$ANDROID_KEYSTORE_ALIAS" \
            --keystore-key-password "$ANDROID_KEYSTORE_KEY_PASSWORD"
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mikuchan@example.com  # Replace with your email
        notify:
          success: true
          failure: true