workflows:
  android-build:
    name: Android Build
    environment:
      # No need to redefine vars here if set in UI
    scripts:
      - name: Debug Environment
        script: |
          #!/bin/bash
          echo "Debugging environment variables:"
          echo "KEYSTORE_FILE is set to: ${KEYSTORE_FILE:-unset}"
          echo "Length of KEYSTORE_FILE: ${#KEYSTORE_FILE}"
          if [ -z "$KEYSTORE_FILE" ]; then
            echo "ERROR: KEYSTORE_FILE is empty or unset"
            exit 1
          fi
          echo "Variable confirmed, proceeding..."
      - name: Decode Keystore
        script: |
          echo "$KEYSTORE_FILE" | base64 -d > keystore.jks